- README.md
Added PYPI API references and examples
> PYPI API references and examples

- pom.xml
- src/main/java/com/artipie/pypi/LiveMeta.java
- src/main/java/com/artipie/pypi/PackagesMeta.java
resolve #14: implement save method (for abstract storage) for the LiveMeta
> resolve #14: implement save method (for abstract storage) for the LiveMeta

- .gitignore
- src/main/java/com/artipie/pypi/ByteFlow.java
- src/main/java/com/artipie/pypi/Flow.java
- src/main/java/com/artipie/pypi/PackagesMeta.java
add ByteFlow that helps to convert string to flow
> resolve #17: add ByteFlow

- pom.xml
- src/test/java/com/artipie/pypi/BinaryArtifactTest.java
- src/test/java/com/artipie/pypi/PackagesMetaTest.java
> added new tests. coverage 98%

- src/test/java/com/artipie/pypi/PypiContainer.java
- src/test/java/com/artipie/pypi/PypiListTCase.java
integrational test fo list operation #43. Disabled becouse of implementation of list operation not finished.
> integrational test fo list operation #43

- src/main/java/com/artipie/pypi/http/Multipart.java
- src/main/java/com/artipie/pypi/http/WheelSlice.java
- src/test/java/com/artipie/pypi/PypiPublishITCase.java
Made `Multipart` and `WheelSlice` save uploads by the correct keys into storage.
> Save upload by name

- pom.xml
> Parent pom upgrade to 0.3.4

- README.md
> #62 - restructure README.md

- src/main/java/com/artipie/pypi/http/PySlice.java
- src/main/java/com/artipie/pypi/http/SliceIndex.java
- src/test/java/com/artipie/pypi/PypiCliITCase.java
- src/test/java/com/artipie/pypi/http/SliceIndexTest.java
For #68 I've corrected `SliceIndex` implementation and added tests for it, also corrected `PySlice` and used it in `PypiCliITCase` to be sure pip understands our index.
> #68 - SliceIndex implementation corrected and tested

- .github/workflows/ci-checks.yml
- src/main/java/com/artipie/pypi/http/Multipart.java
- src/test/java/com/artipie/pypi/http/MultipartTest.java
Fixed build with jdk 8 and added 1.8 to CI checks matrix.
> Fix java 8 build

- pom.xml
- src/main/java/com/artipie/pypi/http/WheelSlice.java
- src/test/java/com/artipie/pypi/http/WheelSliceTest.java
Fixed `WheelSlice` to save content with respect to the request path and added corresponding test.
> #74 - Do not loose path in WheelSlice

- src/main/java/com/artipie/pypi/NormalizedProjectName.java
- src/main/java/com/artipie/pypi/http/WheelSlice.java
- src/test/java/com/artipie/pypi/NormalizedProjectNameTest.java
- src/test/java/com/artipie/pypi/http/WheelSliceTest.java
Part of #59: introduced `NormalizedProjectName` interface and its `FromFilename` implementation. Used this class in `WheelSlice`.
> #59 - introduced NormalizedProjectName

- src/main/java/com/artipie/pypi/http/PySlice.java
- src/test/java/com/artipie/pypi/http/PySliceTest.java
Added test ensure that routing in `PySlice` works as expected and to close #79.
> #79 - test for PySlice

- src/main/java/com/artipie/pypi/http/SliceIndex.java
- src/test/java/com/artipie/pypi/http/PySliceTest.java
- src/test/java/com/artipie/pypi/http/SliceIndexTest.java
Added packages sha256 digest hex to index.html to close #87.
> #87 - package hash to index.html

- pom.xml
- src/test/java/com/artipie/pypi/http/MultipartTest.java
For #67 I've extended `MultipartTest` and set coverage metrics to 0.75.
> #67 - extended MultipartTest and set coverage metrics

- src/main/java/com/artipie/pypi/http/PySlice.java
- src/test/java/com/artipie/pypi/http/PySliceTest.java
Added support for various archive formats on download to close #92.
> #92 - support various archive formats on download

- src/main/java/com/artipie/pypi/NormalizedProjectName.java
- src/main/java/com/artipie/pypi/http/WheelSlice.java
- src/main/java/com/artipie/pypi/meta/ValidFilename.java
- src/test/java/com/artipie/pypi/http/WheelSliceTest.java
- src/test/java/com/artipie/pypi/meta/ValidFilenameTest.java
Added filename validation on upload to close #95.
> #95 - validate filename on upload

- pom.xml
- src/main/java/com/artipie/pypi/http/SliceIndex.java
- src/test/java/com/artipie/pypi/http/PySliceITCase.java
- src/test/java/com/artipie/pypi/http/WheelSliceTest.java
- src/test/java/com/artipie/pypi/meta/MetadataFromArchiveTest.java
Closes #107 - updated asto and http.
> #107 - update asto and http

- pom.xml
- src/main/java/com/artipie/pypi/http/PySlice.java
> Bump http version 0.15.5 -> 0.15.7

- pom.xml
I've removed redundant dependencies and added myself to developer's list.
> Pom clean up

- pom.xml
- src/main/java/com/artipie/pypi/http/PySlice.java
- src/test/java/com/artipie/pypi/http/PySliceITCase.java
Updated http to `0.16.1`, ppom and used permission actions.
> Updated http to 0.16.1

- pom.xml
- src/main/java/com/artipie/pypi/http/PyProxySlice.java
- src/main/java/com/artipie/pypi/http/PySlice.java
- src/test/java/com/artipie/pypi/http/PyProxySliceITCase.java
Part of #126 
Started to implement python proxy with dealing with index requests.
> #126 - proxy index request

- pom.xml
- src/main/java/com/artipie/pypi/http/PySlice.java
- src/test/java/com/artipie/pypi/http/PySliceITCase.java
Closes #131 
Updated http and used `BasicAuthSlice`
> #131 - update http

- src/main/java/com/artipie/pypi/http/IndexProxySlice.java
- src/test/java/com/artipie/pypi/http/IndexProxySliceTest.java
Closes #128 
I've created unit test for `IndexProxySlice` and fixed it to correctly handle all possible cases.
> #128 - added IndexProxySliceTest

- pom.xml
- src/test/java/com/artipie/pypi/http/PySliceITCase.java
Part of #135 
Created test for `pip search`, it's disabled as we do not support search right now
> #135 - test for search command

- pom.xml
- src/main/java/com/artipie/pypi/http/PySlice.java
- src/main/java/com/artipie/pypi/http/SearchSlice.java
- src/test/java/com/artipie/pypi/http/NameFromXmlTest.java
- src/test/java/com/artipie/pypi/http/PySliceITCase.java
- src/test/java/com/artipie/pypi/http/PySliceTest.java
Part of #135 
Added slice for search and class to obtain project name from xml.
> #135 - project name from xml

- pom.xml
- src/main/java/com/artipie/pypi/http/PySlice.java
- src/main/java/com/artipie/pypi/http/SearchSlice.java
- src/test/java/com/artipie/pypi/http/PySliceTest.java
- src/test/java/com/artipie/pypi/http/SearchSliceTest.java
Part of #135 
Implemented branch when requested artifact if not found in `SearchSlice`, added corresponding test, updated http and added 
`SearchSlice` to `PySlice`
> #135 - artifact not found branch

- src/test/java/com/artipie/pypi/http/PyProxySliceAuthITCase.java
Closes #130 
Added test to verify proxy auth works.
> #130 - added test for proxy auth

- src/main/java/com/artipie/pypi/http/SearchSlice.java
- src/test/java/com/artipie/pypi/http/SearchSliceTest.java
Part of #135 
Added branch for found artifact
> #135 - artifact was found on search

- src/test/java/com/artipie/pypi/http/PySliceITCase.java
- src/test/java/com/artipie/pypi/http/SearchSliceTest.java
Closes #135 
Enabled `PySliceITCase#canSearch` IT and extended `SearchSliceTest` to be tested with different packages.
> #135 - search fully implemented

- src/test/java/com/artipie/pypi/http/PyProxySliceITCase.java
Closes #145 
Added IT to make sure redirects are properly handled by proxy.
> #145 - proxy redirects tests

- src/main/java/com/artipie/pypi/http/ProxySlice.java
- src/test/java/com/artipie/pypi/http/ProxySliceTest.java
- src/test/java/com/artipie/pypi/http/PyProxySliceITCase.java
Closes #147 
Added names normalization in proxy and corresponding test.
> #147 - names normalization in proxy

- pom.xml
- src/test/java/com/artipie/pypi/http/ProxySliceTest.java
- src/test/java/com/artipie/pypi/http/PyProxySliceAuthITCase.java
- src/test/java/com/artipie/pypi/http/SearchSliceTest.java
Update asto, http, http-client and ppom.
> #0 - update deps

- pom.xml
- src/main/java/com/artipie/pypi/http/SearchSlice.java
- src/main/java/com/artipie/pypi/http/WheelSlice.java
Closes #155 
Updated asto and http, used `RsError` where necessary
> Updated asto and http
